import type { ActionDefinition } from "../../core/types.ts";

import { s } from "../../core/json-schema.ts";
import { defineProviderAction } from "../../core/provider-definition.ts";
import { xeroAttachmentEntities } from "./file-types.ts";
const id = s.uuid("The Xero resource ID.");
const idem = s.string({ minLength: 1, maxLength: 128 });
const page = {
  page: s.integer({ minimum: 1, default: 1 }),
  page_size: s.integer({ minimum: 1, maximum: 100, default: 50 }),
  sort: s.stringEnum(["Name", "Size", "CreatedDateUTC"]),
  direction: s.stringEnum(["ASC", "DESC"]),
};
const entity = { entity_type: s.stringEnum(xeroAttachmentEntities), entity_id: id };
export const xeroFileActions: ActionDefinition[] = [
  {
    name: "upload_file",
    description: "Upload one transit file to Xero Files or a selected folder. Maximum 10 MB.",
    requiredScopes: ["files"],
    inputSchema: s.object(
      { tenant_id: id, file: s.transitFile(), folder_id: id, idempotency_key: idem },
      { required: ["file"] },
    ),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "list_files",
    description: "List Xero Files with bounded pagination.",
    requiredScopes: ["files.read"],
    inputSchema: s.object({ tenant_id: id, ...page }, { required: [] }),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "get_file",
    description: "Get file metadata.",
    requiredScopes: ["files.read"],
    inputSchema: s.object({ tenant_id: id, file_id: id }, { required: ["file_id"] }),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "create_folder",
    description: "Create a folder in Xero Files.",
    requiredScopes: ["files"],
    inputSchema: s.object(
      { tenant_id: id, name: s.nonEmptyString("The folder name."), idempotency_key: idem },
      { required: ["name"] },
    ),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "list_folders",
    description: "List folders in Xero Files.",
    requiredScopes: ["files.read"],
    inputSchema: s.object({ tenant_id: id, sort: s.string() }, { required: [] }),
    outputSchema: s.array(s.looseObject("Xero metadata.")),
  },
  {
    name: "get_folder",
    description: "Get folder metadata.",
    requiredScopes: ["files.read"],
    inputSchema: s.object({ tenant_id: id, folder_id: id }, { required: ["folder_id"] }),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "get_files_inbox",
    description: "Get the Files inbox folder and its inbound email address.",
    requiredScopes: ["files.read"],
    inputSchema: s.object({ tenant_id: id }, { required: [] }),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "create_file_association",
    description:
      "Associate a Files document with an Accounting object. ObjectType and ObjectGroup use distinct Xero vocabularies; omit them to let Xero infer the type.",
    requiredScopes: ["files"],
    inputSchema: s.object(
      {
        tenant_id: id,
        file_id: id,
        object_id: id,
        object_type: s.stringEnum([
          "Unknown",
          "Accpay",
          "AccPayCredit",
          "AccPayPayment",
          "AccRec",
          "AccRecCredit",
          "AccRecPayment",
          "Adjustment",
          "ApCreditPayment",
          "ApOverPayment",
          "ApOverPaymentPayment",
          "ApOverPaymentSourcePayment",
          "ApPrepayment",
          "ApPrepaymentPayment",
          "ApPrepaymentSourcePayment",
          "ArCreditPayment",
          "ArOverPayment",
          "ArOverpaymentPayment",
          "ArOverpaymentSourcePayment",
          "ArPrepayment",
          "ArPrepaymentPayment",
          "ArPrepaymentSourcePayment",
          "CashPaid",
          "CashRec",
          "ExpPayment",
          "ManJournal",
          "PurchaseOrder",
          "Receipt",
          "Transfer",
          "Account",
          "Contact",
          "Business",
          "Employee",
          "Person",
          "User",
          "Org",
          "FixedAsset",
          "PayRun",
          "PriceListItem",
          "Bank",
          "Current",
          "Equity",
          "Expense",
          "Fixed",
          "Liability",
          "Prepayment",
          "Revenue",
          "Sales",
          "Overheads",
          "Depreciatn",
          "OtherIncome",
          "DirectCosts",
          "Currliab",
          "Termliab",
          "NonCurrent",
          "SalesQuote",
        ]),
        object_group: s.stringEnum([
          "Account",
          "BankTransaction",
          "Contact",
          "CreditNote",
          "Invoice",
          "Item",
          "ManualJournal",
          "Overpayment",
          "Payment",
          "Prepayment",
          "Quote",
          "Receipt",
        ]),
        idempotency_key: idem,
      },
      { required: ["file_id", "object_id"] },
    ),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "list_file_associations",
    description: "List objects associated with a file.",
    requiredScopes: ["files.read"],
    inputSchema: s.object({ tenant_id: id, file_id: id }, { required: ["file_id"] }),
    outputSchema: s.array(s.looseObject("Xero metadata.")),
  },
  {
    name: "list_object_associations",
    description: "List files associated with an object.",
    requiredScopes: ["files.read"],
    inputSchema: s.object({ tenant_id: id, object_id: id, ...page }, { required: ["object_id"] }),
    outputSchema: s.array(s.looseObject("Xero metadata.")),
  },
  {
    name: "get_file_associations_count",
    description: "Get association counts for up to 50 objects.",
    requiredScopes: ["files.read"],
    inputSchema: s.object(
      { tenant_id: id, object_ids: s.array(id, { minItems: 1, maxItems: 50 }) },
      { required: ["object_ids"] },
    ),
    outputSchema: s.record("Association counts keyed by object UUID.", s.integer({ minimum: 0 })),
  },
  {
    name: "delete_file_association",
    description: "Unlink a file from an object. The file itself is retained.",
    requiredScopes: ["files"],
    inputSchema: s.object({ tenant_id: id, file_id: id, object_id: id }, { required: ["file_id", "object_id"] }),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "list_attachments",
    description:
      "List Accounting attachment metadata. Returned API URLs require Xero authorization; use download_attachment for a usable transit URL.",
    requiredScopes: ["accounting.attachments.read"],
    inputSchema: s.object({ tenant_id: id, ...entity }, { required: ["entity_type", "entity_id"] }),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "get_attachment",
    description: "Get metadata for one attachment on an Accounting object.",
    requiredScopes: ["accounting.attachments.read"],
    inputSchema: s.object(
      { tenant_id: id, ...entity, attachment_id: id },
      { required: ["entity_type", "entity_id", "attachment_id"] },
    ),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "upload_attachment",
    description:
      "Upload raw transit-file bytes to an Accounting object. A matching filename replaces the existing attachment. include_online applies only to accounts-receivable invoices and credit notes.",
    requiredScopes: ["accounting.attachments"],
    inputSchema: s.object(
      { tenant_id: id, ...entity, file: s.transitFile(), include_online: s.boolean(), idempotency_key: idem },
      { required: ["entity_type", "entity_id", "file"] },
    ),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "download_attachment",
    description: "Download exactly one attachment ID or filename into transit storage.",
    requiredScopes: ["accounting.attachments.read"],
    inputSchema: s.object(
      { tenant_id: id, ...entity, attachment_id: id, file_name: s.string() },
      { required: ["entity_type", "entity_id"] },
    ),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "download_document_pdf",
    description: "Download an Accounting document PDF into transit storage.",
    requiredScopes: ["accounting.invoices.read"],
    inputSchema: s.object(
      {
        tenant_id: id,
        entity_type: s.stringEnum(["Invoices", "Quotes", "PurchaseOrders", "CreditNotes"]),
        entity_id: id,
      },
      { required: ["entity_type", "entity_id"] },
    ),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "download_file_content",
    description: "Download the bytes of a Xero Files document into transit storage.",
    requiredScopes: ["files.read"],
    inputSchema: s.object({ tenant_id: id, file_id: id }, { required: ["file_id"] }),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
  {
    name: "get_invoice_online_url",
    description: "Get the shareable online invoice URL.",
    requiredScopes: ["accounting.invoices.read"],
    inputSchema: s.object({ tenant_id: id, invoice_id: id }, { required: ["invoice_id"] }),
    outputSchema: s.looseObject("The Xero metadata or transit download response."),
  },
].map((action) => defineProviderAction("xero", action));
